version: 0.0.{build}

image: Ubuntu1804

skip_branch_with_pr: true

install:
  - virtualenv env -p python3.6
  - source env/bin/activate
  - pip install -r requirements.txt

build: off

test_script:
  - pytest .


deploy: off
