# Generated by Django 2.2 on 2019-04-13 22:40

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rollout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_name', models.CharField(choices=[('bar', 'bar'), ('foo', 'foo')], max_length=64)),
                ('subject', models.TextField(choices=[('flippy.subject.IpAddressSubject', 'IP address'), ('flippy.subject.UserSubject', 'User')])),
                ('enable_percentage', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
